<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://change-this-to-the-site-you-are-testing/" />
<title>New Test</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">New Test</td></tr>
</thead><tbody>
<tr>
	<td>function</td>
	<td>func</td>
	<td>shouldFail</td>
</tr>
<tr>
	<td>&nbsp;&nbsp;getEval</td>
	<td>throw new Error(storedVars.shouldFail);</td>
	<td></td>
</tr>
<tr>
	<td>endFunction</td>
	<td></td>
	<td></td>
</tr>
<!-- --- -->
<!--Typing and changing the following true to something else (but equivalent to true) makes the case fail!!! Regardless of whether you save the modified case.-->
<tr>
	<td>getEval</td>
	<td>true&nbsp;&nbsp;&nbsp;</td>
	<td></td>
</tr>
<!-- --- -->
<!--Needed to fail:-->
<tr>
	<td>try</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>&nbsp;&nbsp;getEval</td>
	<td>selenium.doCall( 'func', 'shouldFail=&quot;first failure&quot;', true )</td>
	<td></td>
</tr>
<tr>
	<td>catch</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>&nbsp;&nbsp;getEval</td>
	<td>alert('sync caught')</td>
	<td></td>
</tr>
<tr>
	<td>endTry</td>
	<td></td>
	<td></td>
</tr>
</tbody></table>
</body>
</html>
